export default{
    container:{
        paddingTop:20,
        paddingHorizontal:30,
        flex:1,
        alignItems:'center',
        justifyContent:'space-between',
        height:'100%',
        backgroundColor:'white'
    },
    textInput:{
        borderRadius:30,
        width:'100%',
        borderColor:'#dddddd',
        borderWidth:1,
        padding:8,
        paddingLeft:20,
        fontSize:16
    },
    btn:{
        borderRadius:30,
        padding:10,
        width:'60%',
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'#0D9EDD',
    },
    modalContent:{
        width:'70%',
        borderRadius:10,
        backgroundColor:'white',
        alignItems:'center',
        justifyContent:'center',
        paddingTop:30,
        paddingBottom:30
    },
    digitsView:{
        flex:0.7,
        justifyContent:'space-between',
        flexDirection:'row',
        width:'100%',
        paddingHorizontal:70
    }
    ,
    digitinput:{
        borderRadius:3,
        borderWidth:2,
        borderColor:'#dddddd',
        fontSize:18,
        fontWeight:'bold',
        textAlign:'center',
        width:30,
        height:40
    }, 
}