export default{
    container:{
        backgroundColor:'#0D9EDD',
        width:'100%',
        height:'100%'
    },
    subContainer:{
        borderTopLeftRadius:30,
        borderTopRightRadius:30,
        backgroundColor:'white',
        height:'100%',
        padding:20
    },
    top:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        padding:30,
        paddingTop:50,
        paddingBottom:20
    },
    roundImage:{
        borderRadius:30,
        borderWidth:1,
        borderColor:'white',
        width:50,
        height:50,
        backgroundColor:'grey'
    },
    image:{
        width:30,
        height:30,
    },
    image60:{
        width:60,
        height:60,
    },
    line:{
        height:2,
        width:'100%',
        backgroundColor:'#dddddd',
        marginTop:20
    },
    bottomTabBar:{
        zIndex:1,
        position:'absolute',
        width:'100%',
        height:60,

    },
    plusButton:{
        zIndex:1,
        position:'absolute',
        width:50,
        height:50,
        backgroundColor:'#0D9EDD',
        borderRadius:30,
        justifyContent:'center' ,
        alignItems:'center'
    },
    btn:{
        borderRadius:30,
        padding:10,
        width:'60%',
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'#0D9EDD',
    },
    description:{
        borderRadius:20,
        borderTopLeftRadius:20,
        borderTopRightRadius:20,
        borderWidth:1,
        borderColor:'#dddddd',
        width:'100%',
        height:200,
        backgroundColor:'white',
        padding:20,
        fontSize:16,
        marginTop:20
    },
    selectImage:{
        borderRadius:20,
        borderTopLeftRadius:20,
        borderTopRightRadius:20,
        borderWidth:1,
        borderColor:'#bbbbbb',
        width:'100%',
        height:100,
        marginTop:20,
        borderStyle:'dashed',
        justifyContent:'center',
        alignItems:'center'
    },
    textInput:{
        borderRadius:30,
        width:'100%',
        borderColor:'#dddddd',
        borderWidth:1,
        padding:8,
        paddingLeft:20,
        fontSize:16,
        marginTop:20
    }
}