export default{
    container:{
        position:'absolute',
        zindex:1,        
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        width:'100%',
        height:70,
        backgroundColor:'white'
    },
    tab:{
        height:40,
        width:40,
        borderRadius:20,
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'#0D9EDD'
    },
    DropDownPicker:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        width:'100%',
        borderWidth:2,
        borderRadius:30,
        borderColor:'#eeeeee',
        padding:12,
        paddingHorizontal:20

    },
    dropDownContainerView:{
        position:'absolute',
        zIndex:1,
        maxHeight:130,
        width:'100%',
        borderWidth:2,
        borderColor:'#aaaaaa',
        marginTop:55
     },     
     tabView:{
        width:35,
        height:35,
        justifyContent:'center',
        alignItems:'center',
        borderRadius:20,
        backgroundColor:'#0D9EDD'
    },
    tabView1:{
        width:35,
        height:35,
        justifyContent:'center',
        alignItems:'center',
    },
    bottomTabBar:{
        zIndex:1,
        position:'absolute',
        width:'100%',
        height:100,
        flexDirection:'row',
        justifyContent:'space-around',
        backgroundColor:'white',
        paddingTop:10
    },
}